name: dask_presentation
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=18.2.0
  - backcall=0.1.0
  - blas=1.1=openblas
  - bleach=3.1.0
  - bokeh=1.0.4
  - ca-certificates=2018.11.29
  - certifi=2018.11.29
  - click=7.0
  - cloudpickle=0.6.1
  - cytoolz=0.9.0.1
  - dask=1.0.0
  - dask-core=1.0.0
  - decorator=4.3.0
  - distributed=1.25.2
  - entrypoints=0.3
  - freetype=2.9.1
  - heapdict=1.0.0
  - icu=58.2
  - ipykernel=5.1.0
  - ipython=7.2.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.2
  - jinja2=2.10
  - jpeg=9c
  - jsonschema=3.0.0a3
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_contrib_core=0.3.3
  - jupyter_core=4.4.0
  - jupyter_nbextensions_configurator=0.4.1
  - libcxx=7.0.0
  - libffi=3.2.1
  - libgfortran=3.0.0
  - libpng=1.6.36
  - libsodium=1.0.16
  - libtiff=4.0.10
  - llvm-meta=7.0.0
  - locket=0.2.0
  - markupsafe=1.1.0
  - mistune=0.8.4
  - msgpack-python=0.6.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.4
  - numpy=1.15.4
  - olefile=0.46
  - openblas=0.3.3
  - openssl=1.0.2p
  - packaging=19.0
  - pandas=0.23.4
  - pandoc=2.5
  - pandocfilters=1.4.2
  - parso=0.3.1
  - partd=0.3.9
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pillow=5.4.1
  - prometheus_client=0.5.0
  - prompt_toolkit=2.0.7
  - psutil=5.4.8
  - ptyprocess=0.6.0
  - pygments=2.3.1
  - pyparsing=2.3.1
  - pyqt=5.6.0
  - pyrsistent=0.14.9
  - python=3.6.7
  - python-dateutil=2.7.5
  - pytz=2018.9
  - pyyaml=3.13
  - pyzmq=17.1.2
  - qt=5.6.2
  - qtconsole=4.4.3
  - readline=7.0
  - rise=5.4.1
  - send2trash=1.5.0
  - setuptools=40.6.3
  - sip=4.18.1
  - six=1.12.0
  - sortedcontainers=2.1.0
  - sqlite=3.26.0
  - tblib=1.3.2
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.9
  - toolz=0.9.0
  - tornado=5.1.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - widgetsnbextension=3.4.2
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zict=0.1.3
  - zlib=1.2.11
